<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Lesson 26 - cookie, async, API</title>
</head>


<body>
  <h1>cookie, async, API</h1>

  <script>
    // Стек и очередь


    function main() {

      setTimeout(function greeting() {
        console.log('Hi!') //3 - выбыла из стека -> переместилась в очередь задач -> вернулась в стек
      }, 0)

      console.log('good morning'); //1

      setTimeout(function greet() {
        console.log('Hello1!') //4 - выбыла из стека -> переместилась в очередь задач -> вернулась в стек
      }, 4000)

      console.log('Bye!') // 2
    }

    main()


    //промисы

    // Cоздается промис, который отправляет GET-запрос на сервер и получает данные пользователя с id=2. Если запрос выполняется успешно (HTTP-код ответа 200), то выводятся данные пользователя в формате JSON. Если происходит ошибка (например, пользователь с таким id не найден), то выводится сообщение об ошибке HTTP.

    const promise = fetch('https://jsonplaceholder.typicode.com/users/2');

    promise.then((response) => {
      if (response.ok) {
        console.log(response);
        return response.json();
      } else {
        throw new Error('Ошибка HTTP: ' + response.status);
      }
    }).then((data) => {
      console.log(data); // данные пользователя с id=1
    }).catch((error) => {
      console.error(error); // ошибка HTTP: 404 (например)
    });


    // Состояния Resolve и rejected

    //В этом примере создается промис, который генерирует случайное число через 1 секунду. Если число больше 0.5, то промис переходит в состояние resolve и в консоль выводится результат. Если число меньше или равно 0.5, то промис переходит в состояние rejected и в консоль выводится сообщение об ошибке.


    const promise2 = new Promise((resolve, reject) => {
      setTimeout(() => {
        const randomNumber = Math.random();
        if (randomNumber > 0.5) {
          resolve(randomNumber);
        } else {
          reject(new Error('Случилась ошибка!'));
        }
      }, 1000);
    });

    promise2.then((result) => {
      console.log('Результат:', result);
    }).catch((error) => {
      console.error('Ошибка:', error.message);
    });


    //Используем ключевое слово async для обозначения асинхронной функции. Затем мы делаем запрос к API с помощью функции fetch и ждем ответ с помощью ключевого слова await. После этого мы преобразуем полученные данные в объект с помощью метода json(). Если запрос выполнен успешно, мы возвращаем данные из функции. В случае ошибки мы выводим сообщение об ошибке в консоль.

    // Затем мы вызываем функцию getData() и используем метод.then() для вывода данных в консоль после их получения.

    async function getData() {
      try {
        const response = await fetch('https://jsonplaceholder.typicode.com/posts/1');
        const data = await response.json();
        return data;
      } catch (error) {
        console.error(error);
      }
    }
    getData().then(data => console.log(data));


  </script>
</body>

</html>